config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do

  resources :records

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  get "calendar/index"

  authenticated :user do
    root :to => 'transmissions#index'
  end
  root :to => 'home#index'
  
  devise_for :users
  resources :users
  resources :roles
    
  get "transmissions/index"
  get "transmissions/test_video"
  get "transmissions/stream_internal"
  get "transmissions/audio"
  get "transmissions/test_audio"
  get "transmissions/auth"
end

app/controllers/transmissions_controller.rb
class TransmissionsController < ApplicationController
	before_filter :authenticate_user!, :except => :auth
    
    @@Sessions = {}
    
  def create_session_token
    @session_token = rand(100000000).to_s
    @@Sessions[@session_token] = Time.now + 60
  end

  def index
  	authorize_for :admin, :internal_video, :public_video 
  end

  def stream_internal
  	authorize_for :admin, :internal_video
    create_session_token
  end
  
  def audio
    authorize_for :admin, :audio
    create_session_token
  end
  
  def test_audio
    authorize_for :admin, :audio
    create_session_token
  end

  def test_video
    authorize_for :admin, :internal_video, :public_video 
    create_session_token
  end
  
  def auth
    token = params[:token]
    return head(:not_authorised) if !token
    expire_at = @@Sessions[token]
    return head(:not_found) if !expire_at
    if expire_at < Time.now
      @@Sessions.delete(token)
      return head(:request_timeout)
    end
    return head(:ok)
  end
  
  def authorize_for(*args)
    if !current_user.has_any_role?(*args)
  	redirect_to root_path, :alert => t('not_authorised')
  	end
  end
  
end

app/helpers/transmissions_helper.rb
module TransmissionsHelper
end

app/views/transmissions/_navigation.html.erb
<% if current_user.has_any_role?(:admin,:internal_video,:public_video) %>
   <div class="navbar">
		<div class="navbar-inner">
			<a class="brand" href="#"><%= t('video_title_transmission_link') %></a>
			<ul class="nav"> 
				<%if !current_user.has_any_role?(:public_video) %>
			      <li>
			        <%= link_to t('internal_transmission_link'), transmissions_stream_internal_path %>  
			      </li>
			    <% end %>
			    <li class="divider-vertical"></li>
			    <li>
			    <%= link_to t('test_video_transmission_link'), transmissions_test_video_path %>  
			    </li>		  
			</ul>
	  </div>
	</div>
<% end %>

<% if current_user.has_any_role?(:admin,:audio) %>
   <div class="navbar">
    	<div class="navbar-inner">
			<a class="brand" href="#"><%= t('audio_title_transmission_link') %></a>
			<ul class="nav"> 
				<li>
			        <%= link_to t('audio_transmission_link'), transmissions_audio_path %>  
			     </li>
			    <li class="divider-vertical"></li>
			    <li>
			    <%= link_to t('test_audio_transmission_link'), transmissions_test_audio_path %>  
			    </li>		  
			</ul>
	  </div>
	</div>
<% end %>

app/views/transmissions/audio.html.erb
<div align=center>

<object width="320" height="200"> 
<param name="movie" value="http://fpdownload.adobe.com/strobe/FlashMediaPlayback_101.swf"></param>
<param name="flashvars" value="src=http://ltu.no-ip.info:8082/live/audio_hall/manifest.f4m?session=<%= @session_token %>"></param>
<param name="allowFullScreen" value="true"></param>
<param name="allowscriptaccess" value="always"></param>
<embed src="http://fpdownload.adobe.com/strobe/FlashMediaPlayback_101.swf" type="application/x-shockwave-flash" allowscriptaccess="always" 
allowfullscreen="true" width="320" height="320" 
flashvars="src=http://ltu.no-ip.info:8082/live/audio_hall/manifest.f4m?session=<%= @session_token %>"></embed>
</object>
</div>

</br></br></br>

<%= render 'transmissions/navigation' %>

app/views/transmissions/index.html.erb
<%= render 'transmissions/navigation' %>

app/views/transmissions/stream_internal.html.erb
<div align=center>

<script type="text/javascript">
            
            // Collect query parameters in an object that we can
            // forward to SWFObject:
            
            var pqs = new ParsedQueryString();
            var parameterNames = pqs.params(false);
            var parameters = {
                src: "http://ltu.no-ip.info:8080/lighthouse_hall/manifest.f4m?session=<%= @session_token %>",
                autoPlay: "false",
                verbose: true,
                controlBarAutoHide: "false",
                controlBarPosition: "bottom"
            };
            
            for (var i = 0; i < parameterNames.length; i++) {
                var parameterName = parameterNames[i];
                parameters[parameterName] = pqs.param(parameterName) ||
                parameters[parameterName];
            }
            
               var wmodeValue = "direct";
            var wmodeOptions = ["direct", "opaque", "transparent", "window"];
            if (parameters.hasOwnProperty("wmode"))
            {
                if (wmodeOptions.indexOf(parameters.wmode) >= 0)
            	{
            		wmodeValue = parameters.wmode;
            	}	            	
            	delete parameters.wmode;
            }
            
            // Embed the player SWF:	            
            swfobject.embedSWF(
				"/flash/StrobeMediaPlayback.swf"
				, "StrobeMediaPlayback"
				, 500
				, 374
				, "10.1.0"
				, "/flash/expressInstall.swf"
				, parameters
				, {
	                allowFullScreen: "true",
	                wmode: wmodeValue
	            }
				, {
	                name: "StrobeMediaPlayback"
	            }
			);
            
        </script>

                    <div id="StrobeMediaPlayback">
                        <p>
                            Alternative content
                        </p>
                    </div>

</div>

</br></br></br>

<%= render 'transmissions/navigation' %>

app/views/transmissions/test_audio.html.erb
<%= javascript_include_tag "application"  %>

<div align=center>


<object width="500" height="384"> 
<param name="movie" value="/flash/StrobeMediaPlayback.swf"></param>
<param name="flashvars" value="src=http://ltu.no-ip.info:8082/test/music.mp3/manifest.f4m?session=<%= @session_token %>"></param>
<param name="allowFullScreen" value="true"></param>
<param name="allowscriptaccess" value="always"></param>
<embed src="/flash/StrobeMediaPlayback.swf" type="application/x-shockwave-flash" allowscriptaccess="always" 
allowfullscreen="true" width="384" height="376" 
flashvars="src=http://ltu.no-ip.info:8082/test/music.mp3/manifest.f4m?session=<%= @session_token %>"></embed>
</object>

</br></br>

<video 
    src="/videos/test/music.mp3" 
    height="220" 
    id="container" 
    poster="/videos/test/music.mp3"
    width="500">
</video>

<script type="text/javascript">
    jwplayer("container").setup({
        flashplayer: "/flash/player.swf"
    });
</script>

</div>

</br></br></br>

<%= render 'transmissions/navigation' %>

app/views/transmissions/test_video.html.erb
<%= javascript_include_tag "application"  %>

<script type="text/javascript">
            
            // Collect query parameters in an object that we can
            // forward to SWFObject:
            
            var pqs = new ParsedQueryString();
            var parameterNames = pqs.params(false);
            var parameters = {
                src: "http://ltu.no-ip.info:8080/test/video.mp4/manifest.f4m?session=<%= @session_token %>",
                autoPlay: "false",
                verbose: true,
                controlBarAutoHide: "false",
                controlBarPosition: "bottom",
                poster: "/videos/test/video.jpg"
            };
            
            for (var i = 0; i < parameterNames.length; i++) {
                var parameterName = parameterNames[i];
                parameters[parameterName] = pqs.param(parameterName) ||
                parameters[parameterName];
            }
            
               var wmodeValue = "direct";
            var wmodeOptions = ["direct", "opaque", "transparent", "window"];
            if (parameters.hasOwnProperty("wmode"))
            {
            	if (wmodeOptions.indexOf(parameters.wmode) >= 0)
            	{
            		wmodeValue = parameters.wmode;
            	}	            	
            	delete parameters.wmode;
            }
            
            // Embed the player SWF:	            
            swfobject.embedSWF(
				"/flash/StrobeMediaPlayback.swf"
				, "StrobeMediaPlayback"
				, 500
				, 376
				, "10.1.0"
				, "/flash/expressInstall.swf"
				, parameters
				, {
	                allowFullScreen: "true",
	                wmode: wmodeValue
	            }
				, {
	                name: "StrobeMediaPlayback"
	            }
			);
            
        </script>
<div align=center>

                    <div id="StrobeMediaPlayback">
                        <p>
                            Alternative content
                        </p>
                    </div>
</div>
                    
</br></br></br>

<%= render 'transmissions/navigation' %>