config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do

  resources :records

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  get "calendar/index"

  authenticated :user do
    root :to => 'transmissions#index'
  end
  root :to => 'home#index'
  
  devise_for :users
  resources :users
  resources :roles
    
  get "transmissions/index"
  get "transmissions/test_video"
  get "transmissions/stream_internal"
  get "transmissions/audio"
  get "transmissions/test_audio"
  get "transmissions/auth"
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :city

  validates_presence_of :name
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => t('not_authorised')
    @users = User.all
  end

  def show
    authorize! :show, @user, :message => t('not_authorised')
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => t('not_authorised')
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => t('user_updated')
    else
      redirect_to users_path, :alert => t('user_cannot_be_updated')
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => t('not_authorised')
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => t('user_deleted')
    else
      redirect_to users_path, :notice => t('cannot_delete_yourself')
    end
  end
end

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-vertical' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3><%= ('change_role_link') %></h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline' %>
    </div>
    <div class="modal-footer">
      <%= f.submit t('change_role_link'), :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#"><%= t('close_link') %></a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h3><%= t :manage_users_title %></h3>
<div class="span8">
<table class="table table-condensed">
	  <thead>
      <tr>
          <th><%= t('user_field') %></th>
          <th><%= t('email_field') %></th>
          <th><%= t('city_field') %></th>
          <th><%= t('registered_field') %></th>
          <th><%= t('role_field') %></th>
          <th></th>
          <th></th>                                      
      </tr>
  </thead>   
  <tbody>
  <% @users.each do |user| %>
    <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.email %></td>
        <td><%= user.city %></td>
        <td><%= user.created_at.to_date %></td>
        <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
        <td>
          <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button"><%= t('change_role_link') %></a>
          <%= render user %>
        </td>
        <td><%= link_to(t('delete_user_link'), user_path(user), :data => { :confirm => "Вы уверены?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>                                       
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to t(:roles_link), roles_path %>
</div>