config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do

  resources :records

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  get "calendar/index"

  authenticated :user do
    root :to => 'transmissions#index'
  end
  root :to => 'home#index'
  
  devise_for :users
  resources :users
  resources :roles
    
  get "transmissions/index"
  get "transmissions/test_video"
  get "transmissions/stream_internal"
  get "transmissions/audio"
  get "transmissions/test_audio"
  get "transmissions/auth"
end

app/models/record.rb
class Record < ActiveRecord::Base
  attr_accessible :ip, :name, :refferer, :request_type, :user
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  # GET /records
  # GET /records.json
  def index
    @records = Record.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @records }
    end
  end

  # GET /records/1
  # GET /records/1.json
  def show
    @record = Record.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @record }
    end
  end

  # GET /records/new
  # GET /records/new.json
  def new
    @record = Record.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @record }
    end
  end

  # GET /records/1/edit
  def edit
    @record = Record.find(params[:id])
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(params[:record])

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render json: @record, status: :created, location: @record }
      else
        format.html { render action: "new" }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /records/1
  # PUT /records/1.json
  def update
    @record = Record.find(params[:id])

    respond_to do |format|
      if @record.update_attributes(params[:record])
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record = Record.find(params[:id])
    @record.destroy

    respond_to do |format|
      format.html { redirect_to records_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<%= simple_form_for(@record) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user %>
    <%= f.input :name %>
    <%= f.input :ip %>
    <%= f.input :request_type %>
    <%= f.input :refferer %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1>Editing record</h1>

<%= render 'form' %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<h1>Listing records</h1>

<table>
  <tr>
    <th>User</th>
    <th>Name</th>
    <th>Ip</th>
    <th>Request type</th>
    <th>Refferer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @records.each do |record| %>
  <tr>
    <td><%= record.user %></td>
    <td><%= record.name %></td>
    <td><%= record.ip %></td>
    <td><%= record.request_type %></td>
    <td><%= record.refferer %></td>
    <td><%= link_to 'Show', record %></td>
    <td><%= link_to 'Edit', edit_record_path(record) %></td>
    <td><%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Record', new_record_path %>

app/views/records/new.html.erb
<h1>New record</h1>

<%= render 'form' %>

<%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @record.user %>
</p>

<p>
  <b>Name:</b>
  <%= @record.name %>
</p>

<p>
  <b>Ip:</b>
  <%= @record.ip %>
</p>

<p>
  <b>Request type:</b>
  <%= @record.request_type %>
</p>

<p>
  <b>Refferer:</b>
  <%= @record.refferer %>
</p>


<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>