config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do

  resources :records

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  get "calendar/index"

  authenticated :user do
    root :to => 'transmissions#index'
  end
  root :to => 'home#index'
  
  devise_for :users
  resources :users
  resources :roles
    
  get "transmissions/index"
  get "transmissions/test_video"
  get "transmissions/stream_internal"
  get "transmissions/audio"
  get "transmissions/test_audio"
  get "transmissions/auth"
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController

  def index
    @roles = Role.all
  end

  def show
    @roles = Role.find(params[:id])
  end

  def new
    @roles = Role.new
  end

  def edit
    @roles = Role.find(params[:id])
  end

  def create
    @roles = Role.new(params[:roles])

    respond_to do |format|
      if @roles.save
        format.html { redirect_to @roles, notice: 'roles was successfully created.' }
        format.json { render json: @roles, status: :created, location: @roles }
      else
        format.html { render action: "new" }
        format.json { render json: @roles.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @roles = Role.find(params[:id])

    respond_to do |format|
      if @roles.update_attributes(params[:roles])
        format.html { redirect_to @roles, notice: 'roles was successfully updated---.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @roles.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @roles = Role.find(params[:id])
    @roles.destroy

    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= simple_form_for(@roles) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1><%= t :role_edit_link %></h1>

<%= simple_form_for(@roles, :html => { :class => 'form-vertical' }) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name, :label => false %>
  <%= f.button :submit, t('update_link'), :class => 'btn-primary' %>
<% end %>

<%= link_to t(:uni_posessors_link), @roles %> |
<%= link_to t(:back_link), roles_path %>

app/views/roles/index.html.erb
<h1><%= t :roles_title %></h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @roles.each do |role| %>
  <tr>
    <td><%= role.name %></td>
    <td><%= link_to t(:uni_posessors_link), role, :class => 'btn btn-mini' %></td>
    <td><%= link_to t(:uni_edit_link), edit_role_path(role), :class => 'btn btn-mini' %></td>
    <td><%= link_to t(:uni_delete_link), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t(:role_new_title), new_role_path %>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<%= @roles.inspect %>

<p>
    <%= @roles.name %>
</p>

app/views/roles/update.html.erb
<h1><%= t :role_edit_link %></h1>

<%= simple_form_for(@roles, :html => { :method => :put, :class => 'form-vertical' }) do |f| %>
  <%= f.input :name, :label => false %>
  <%= f.button :submit, t('update_link'), :class => 'btn-primary' %>
<% end %>

<%= link_to t(:uni_posessors_link), @roles %> |
<%= link_to t(:back_link), roles_path %>